<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
//$label = NULL;
//$position = NULL;
//$display = NULL;
//$label_image = NULL;
//if ($_product->getIsLabel()) {
//    if ($_product->getIsEnabledLabel()) {
//        $display = $_product->getLabelDisplay();
//        $position = $_product->getLabelPosition();
//        $label_image = $_product->getLabelImage();
//    } else {
//        $display = Mage::getStoreConfig('label/label_group/label_display');
//        $position = Mage::getStoreConfig('label/label_group/label_position');
//        $label_image = Mage::getStoreConfig('label/label_group/label_image');
//    }
//}
//if($display == '1' || $display == '2'){
//    $label = 1;
//    switch ($position) {
//    case 'topleft':
//        $position = "top left";
//        break;
//    case 'topright':
//        $position = "top right";
//        break;
//    case 'bottomleft':
//        $position = "bottom left";
//        break;
//    case 'bottomright':
//        $position = "bottom right";
//        break;
//}
//    }
//else{$label = 0;}
//Zend_Debug::dump($_product->getData());
?>

<script type="text/javascript">
  optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="tabproduct-view">
    <div class="product-essential">
        <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>

                <div class="product-shop">
                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    </div>
                          <?php if ($_product->getShortDescription()): ?>
                                            <div class="short-description">
                                               <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                                            </div>
<?php endif; ?>
<?php if ($this->canEmailToFriend()): ?>
                        <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
                <?php endif; ?>

                <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
<?php echo $this->getChildHtml('alert_urls') ?>
                                <?php echo $this->getChildHtml('extrahint') ?>
                <ul id="tabs" class="subsection_tabs">
                    <li class="tab"><a href="#product-options-wrapper">Color & Sizes</a></li>
                    <li class="tab"><a href="#product-info">Description</a></li>
                </ul>
                     
                <div id="product-info" class="tab-element">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html): ?>
                        <div class="box-collateral <?php echo "box-{$alias}" ?>">
                    <?php if ($title = $this->getChildData($alias, 'title')): ?>
                            <h2><?php echo $this->escapeHtml($title); ?></h2>
            
          
                        <?php endif; ?>
<?php echo $html; ?>
                            <div style="display:none;">    <?php echo $this->getChildHtml('product_type_data') ?></div>
                    </div>
                        <?php endforeach; ?>
<?php echo $this->getChildHtml('upsell_products') ?>
                    <?php echo $this->getChildHtml('product_additional_data') ?>

                    </div>
                    <?php if (!$this->hasOptions()): ?>

                        <div class="add-to-box">
<?php if ($_product->isSaleable()): ?>
<?php echo $this->getChildHtml('addtocart') ?>

<?php endif; ?>
                 
                                </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
<?php else: ?>
              
                <?php endif; ?>

          

                <?php echo $this->getChildHtml('other'); ?>

                <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif; ?>

                                            </div>

                                            <div class="product-img-box" style="position:relative;">
<?php if ($label): ?>
                                                    <div class="product-img-label" style="position:absolute; height:370px; width:370px; top:26px; left:46px; z-index: 900; pointer-events: none;background: url('/media/catalog/product/<?php echo $label_image; ?>') <?php echo $position; ?> no-repeat"></div>
                <?php endif; ?>
<?php echo $this->getChildHtml('media') ?>
                                                </div>

                                                <div class="clearer"></div>
<?php if ($_product->isSaleable() && $this->hasOptions()): ?>
<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif; ?>
        </form>
        <script type="text/javascript">
        productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(){ if (this.validator.validate()) { this.form.submit();}}.bind(productAddToCartForm);
      </script>
    </div>


</div>
